__work log - confusion matrix__

 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Setup" data-toc-modified-id="Setup-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Setup</a></span><ul class="toc-item"><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Setup---Imports" data-toc-modified-id="Setup---Imports-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Setup - Imports</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Setup---Initialize-Django" data-toc-modified-id="Setup---Initialize-Django-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Setup - Initialize Django</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Setup---Tools" data-toc-modified-id="Setup---Tools-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Setup - Tools</a></span></li></ul></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Build-Confusion-Matrix-Data" data-toc-modified-id="Build-Confusion-Matrix-Data-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Build Confusion Matrix Data</a></span><ul class="toc-item"><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Person-detection" data-toc-modified-id="Person-detection-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Person detection</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Person-lookup" data-toc-modified-id="Person-lookup-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Person lookup</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Person-type" data-toc-modified-id="Person-type-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Person type</a></span><ul class="toc-item"><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Person-type---Subjects" data-toc-modified-id="Person-type---Subjects-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Person type - Subjects</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Person-type---Sources" data-toc-modified-id="Person-type---Sources-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Person type - Sources</a></span></li></ul></li></ul></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Notes" data-toc-modified-id="Notes-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Notes</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#TODO" data-toc-modified-id="TODO-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>TODO</a></span><ul class="toc-item"><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#TODO---filter-articles-that-are-not-news" data-toc-modified-id="TODO---filter-articles-that-are-not-news-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>TODO - filter articles that are not news</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#Debugging" data-toc-modified-id="Debugging-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Debugging</a></span></li></ul></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#DONE" data-toc-modified-id="DONE-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>DONE</a></span></li><li><span><a href="https://research.local:8000/user/jonathanmorgan/notebooks/work/sourcenet/django/research/work/msu_phd_work/2017.09.20-work_log-confusion_matrix.ipynb#NEXT" data-toc-modified-id="NEXT-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>NEXT</a></span></li></ul></div>

# Setup

- Back to [Table of Contents](#Table-of-Contents)

## Setup - Imports

- Back to [Table of Contents](#Table-of-Contents)

In [20]:
import datetime
import json
import numpy
import pandas
import patsy
import sklearn
import sklearn.metrics
import six
import statsmodels
import statsmodels.api

print( "packages imported at " + str( datetime.datetime.now() ) )

packages imported at 2017-09-21 03:36:10.705711


/home/jonathanmorgan/.virtualenvs/sourcenet/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
%pwd

'/home/jonathanmorgan/work/sourcenet/django/research/work/msu_phd_work'

## Setup - Initialize Django

- Back to [Table of Contents](#Table-of-Contents)

First, initialize my dev django project, so I can run code in this notebook that references my django models and can talk to the database using my project's settings.

You need to have installed your virtualenv with django as a kernel, then select that kernel for this notebook.

In [3]:
%run django_init.py

django initialized at 2017-09-21 01:47:01.973604


Import any `sourcenet` or `sourcenet_analysis` models or classes.

In [4]:
# sourcenet_analysis models.
from sourcenet_analysis.models import Reliability_Names

print( "sourcenet and sourcenet_analysis packages imported at " + str( datetime.datetime.now() ) )

sourcenet and sourcenet_analysis packages imported at 2017-09-21 01:47:05.297395


## Setup - Tools

- Back to [Table of Contents](#Table-of-Contents)

Write functions here to do math, so that we can reuse said tools below.

# Build Confusion Matrix Data

- Back to [Table of Contents](#Table-of-Contents)

A basic confusion matrix ( [https://en.wikipedia.org/wiki/Confusion_matrix](https://en.wikipedia.org/wiki/Confusion_matrix) ) contains counts of true positives, true negatives, false positives, and false negatives for a given binary or boolean (yes/no) classification decision you are asking someone or something to make.

To create a confusion matrix, you need two associated vectors containing classification decisions (0s and 1s), one that contains ground truth, and one that contains values predicted by whatever coder you are testing.  For each associated pair of values:

- Start with the predicted value: positive (1) or negative (0).
- Look at the corresponding ground truth value.  If they match, it is "true".  If not, it is "false".
- So, predicted 1 and ground_truth 1 is a "true positive".
- Add one to the counter for the class of prediction: "true positive", "true negative", "false positive", "false negative".

Once you have your basic confusion matrix, the counts of true positives, true negatives, false positives, and false negatives can then be used to calculate a set of different scores and values one can use to assess the quality of predictive models.  These scores include "precision and recall", "accuracy", an "F1 score" (a harmonic mean), and a "diagnostic odds ratio", among many others.

## Person detection

- Back to [Table of Contents](#Table-of-Contents)

For each person detected across the set of articles, look at whether the automated coder correctly detected the person, independent of eventual lookup or person type.

In [10]:
# declare variables
reliability_names_label = None
label_in_list = []
reliability_names_qs = None
ground_truth_coder_index = 1
predicted_coder_index = 2

# processing
column_name = ""
predicted_value = -1
predicted_list = []
ground_truth_value = -1
ground_truth_list = []
ground_truth_positive_count = -1
predicted_positive_count = -1
true_positive_count = -1
false_positive_count = -1
ground_truth_negative_count = -1
predicted_negative_count = -1
true_negative_count = -1
false_negative_count = -1
reliability_names_instance = None

# set label
reliability_names_label = "prelim_month"

# lookup Reliability_Names for selected label
label_in_list.append( reliability_names_label )
reliability_names_qs = Reliability_Names.objects.filter( label__in = label_in_list )

print( "Found " + str( reliability_names_qs.count() ) + " rows with label in " + str( label_in_list ) )

# loop over records
predicted_value = -1
predicted_list = []
ground_truth_value = -1
ground_truth_list = []
ground_truth_positive_count = 0
predicted_positive_count = 0
true_positive_count = 0
false_positive_count = 0
ground_truth_negative_count = 0
predicted_negative_count = 0
true_negative_count = 0
false_negative_count = 0
for reliability_names_instance in reliability_names_qs:
    
    # get detected flag from ground truth and predicted columns and add them to list.
    
    # ==> ground truth
    column_name = Reliability_Names.FIELD_NAME_PREFIX_CODER
    column_name += str( ground_truth_coder_index )
    column_name += "_" + Reliability_Names.FIELD_NAME_SUFFIX_DETECTED
    ground_truth_value = getattr( reliability_names_instance, column_name )
    ground_truth_list.append( ground_truth_value )
    
    # ==> predicted
    column_name = Reliability_Names.FIELD_NAME_PREFIX_CODER
    column_name += str( predicted_coder_index )
    column_name += "_" + Reliability_Names.FIELD_NAME_SUFFIX_DETECTED
    predicted_value = getattr( reliability_names_instance, column_name )
    predicted_list.append( predicted_value )
    
    # add to counts
    
    # ==> ground truth
    if ( ground_truth_value == 0 ):
        
        # ground truth negative
        ground_truth_negative_count += 1
        
    # not zero - so 1 (or supports other integer values)
    else:

        # ground truth positive
        ground_truth_positive_count += 1
                
    #-- END check to see if positive or negative --# 
    
    
    if ( predicted_value == 0 ):
        
        # predicted negative
        predicted_negative_count += 1
        
        # equal to ground_truth?
        if ( predicted_value == ground_truth_value ):
            
            # true negative
            true_negative_count += 1
            
        else:
            
            # false negative
            false_negative_count += 1
            
        #-- END check to see if true or false --#
        
    # not zero - so 1 (or supports other integer values)
    else:

        # predicted positive
        predicted_positive_count += 1
        
        # equal to ground_truth?
        if ( predicted_value == ground_truth_value ):
            
            # true positive
            true_positive_count += 1
            
        else:
            
            # false positive
            false_positive_count += 1
            
        #-- END check to see if true or false --#
        
    #-- END check to see if positive or negative --# 
        
#-- END loop over Reliability_Names instances. --#

print( "==> Predicted positives: " + str( predicted_positive_count ) )
print( "==> Ground truth positives: " + str( ground_truth_positive_count ) )
print( "==> True positives: " + str( true_positive_count ) )
print( "==> False positives: " + str( false_positive_count ) )
print( "==> Predicted negatives: " + str( predicted_negative_count ) )
print( "==> Ground truth negatives: " + str( ground_truth_negative_count ) )
print( "==> True negatives: " + str( true_negative_count ) )
print( "==> False negatives: " + str( false_negative_count ) )
print( "==> Precision (true positive/predicted positive): " + str( ( true_positive_count / predicted_positive_count ) ) )
print( "==> Recall (true positive/ground truth positive): " + str( ( true_positive_count / ground_truth_positive_count ) ) )


Found 2446 rows with label in ['prelim_month']
==> Predicted positives: 2383
==> Ground truth positives: 2378
==> True positives: 2315
==> False positives: 68
==> Predicted negatives: 63
==> Ground truth negatives: 68
==> True negatives: 0
==> False negatives: 63
==> Precision (true positive/predicted positive): 0.9714645404951742
==> Recall (true positive/ground truth positive): 0.9735071488645921


In [13]:
# loop over lists to derive counts
predicted_value = -1
ground_truth_value = -1
ground_truth_positive_count = 0
predicted_positive_count = 0
true_positive_count = 0
false_positive_count = 0
ground_truth_negative_count = 0
predicted_negative_count = 0
true_negative_count = 0
false_negative_count = 0
list_index = -1
for predicted_value in predicted_list:

    # increment index and get associated item from ground_truth_list
    list_index += 1
    ground_truth_value = ground_truth_list[ list_index ]
    
    # add to counts
    
    # ==> ground truth
    if ( ground_truth_value == 0 ):
        
        # ground truth negative
        ground_truth_negative_count += 1
        
    # not zero - so 1 (or supports other integer values)
    else:

        # ground truth positive
        ground_truth_positive_count += 1
                
    #-- END check to see if positive or negative --# 
    
    
    if ( predicted_value == 0 ):
        
        # predicted negative
        predicted_negative_count += 1
        
        # equal to ground_truth?
        if ( predicted_value == ground_truth_value ):
            
            # true negative
            true_negative_count += 1
            
        else:
            
            # false negative
            false_negative_count += 1
            
        #-- END check to see if true or false --#
        
    # not zero - so 1 (or supports other integer values)
    else:

        # predicted positive
        predicted_positive_count += 1
        
        # equal to ground_truth?
        if ( predicted_value == ground_truth_value ):
            
            # true positive
            true_positive_count += 1
            
        else:
            
            # false positive
            false_positive_count += 1
            
        #-- END check to see if true or false --#
        
    #-- END check to see if positive or negative --# 

#-- END loop over list items. --#
    
print( "==> Predicted positives: " + str( predicted_positive_count ) + " ( " + str( ( true_positive_count + false_positive_count ) ) + " )" )
print( "==> Ground truth positives: " + str( ground_truth_positive_count ) )
print( "==> True positives: " + str( true_positive_count ) )
print( "==> False positives: " + str( false_positive_count ) )
print( "==> Predicted negatives: " + str( predicted_negative_count ) + " ( " + str( ( true_negative_count + false_negative_count ) ) + " )" )
print( "==> Ground truth negatives: " + str( ground_truth_negative_count ) )
print( "==> True negatives: " + str( true_negative_count ) )
print( "==> False negatives: " + str( false_negative_count ) )
print( "==> Precision (true positive/predicted positive): " + str( ( true_positive_count / predicted_positive_count ) ) )
print( "==> Recall (true positive/ground truth positive): " + str( ( true_positive_count / ground_truth_positive_count ) ) )


==> Predicted positives: 2383 ( 2383 )
==> Ground truth positives: 2378
==> True positives: 2315
==> False positives: 68
==> Predicted negatives: 63 ( 63 )
==> Ground truth negatives: 68
==> True negatives: 0
==> False negatives: 63
==> Precision (true positive/predicted positive): 0.9714645404951742
==> Recall (true positive/ground truth positive): 0.9735071488645921


In [19]:
# try scikit-learn: http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html
sklearn.metrics.precision_recall_fscore_support( ground_truth_list, predicted_list )

(array([ 0.        ,  0.97146454]),
 array([ 0.        ,  0.97350715]),
 array([ 0.        ,  0.97248477]),
 array([  68, 2378]))

In [27]:
# scikit-learn confusion matrix
# http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
conf_matrix = sklearn.metrics.confusion_matrix( ground_truth_list, predicted_list )
print( str( conf_matrix ) )

# get counts in variables
true_positive_count = conf_matrix[ 1 ][ 1 ]
false_positive_count = conf_matrix[ 0 ][ 1 ]
true_negative_count = conf_matrix[ 0 ][ 0 ]
false_negative_count = conf_matrix[ 1 ][ 0 ]

print( "==> Predicted positives: " + str( predicted_positive_count ) + " ( " + str( ( true_positive_count + false_positive_count ) ) + " )" )
print( "==> Ground truth positives: " + str( ground_truth_positive_count ) )
print( "==> True positives: " + str( true_positive_count ) )
print( "==> False positives: " + str( false_positive_count ) )
print( "==> Predicted negatives: " + str( predicted_negative_count ) + " ( " + str( ( true_negative_count + false_negative_count ) ) + " )" )
print( "==> Ground truth negatives: " + str( ground_truth_negative_count ) )
print( "==> True negatives: " + str( true_negative_count ) )
print( "==> False negatives: " + str( false_negative_count ) )
print( "==> Precision (true positive/predicted positive): " + str( ( true_positive_count / predicted_positive_count ) ) )
print( "==> Recall (true positive/ground truth positive): " + str( ( true_positive_count / ground_truth_positive_count ) ) )


[[   0   68]
 [  63 2315]]
==> Predicted positives: 2383 ( 2383 )
==> Ground truth positives: 2378
==> True positives: 2315
==> False positives: 68
==> Predicted negatives: 63 ( 63 )
==> Ground truth negatives: 68
==> True negatives: 0
==> False negatives: 63
==> Precision (true positive/predicted positive): 0.971464540495
==> Recall (true positive/ground truth positive): 0.973507148865


In [25]:
# pandas
# https://stackoverflow.com/questions/2148543/how-to-write-a-confusion-matrix-in-python
y_actu = pandas.Series( ground_truth_list, name='Actual')
y_pred = pandas.Series( predicted_list, name='Predicted')
df_confusion = pandas.crosstab(y_actu, y_pred)
print( str( df_confusion ) )

Predicted   0     1
Actual             
0           0    68
1          63  2315


More to look into:

- https://stackoverflow.com/questions/39626401/how-to-get-odds-ratios-and-other-related-features-with-scikit-learn#39711837

## Person lookup

- Back to [Table of Contents](#Table-of-Contents)

For each person detected across the set of articles, look at whether the automated coder correctly looked up the person (so compare person IDs).

## Person type

- Back to [Table of Contents](#Table-of-Contents)

For each person detected across the set of articles, look at whether the automated coder assigned the correct type.

### Person type - Subjects

- Back to [Table of Contents](#Table-of-Contents)

For each person detected across the set of articles classified by Ground truth as a subject, look at whether the automated coder assigned the correct person type.

### Person type - Sources

- Back to [Table of Contents](#Table-of-Contents)

For each person detected across the set of articles classified by Ground truth as a source, look at whether the automated coder assigned the correct person type.

# Notes

- Back to [Table of Contents](#Table-of-Contents)

# TODO

- Back to [Table of Contents](#Table-of-Contents)

TODO:

- add field to article table for non-news or is_hard_news.
- Article 22181 - Why is the incorrect person "Christian Reformed Church" tagged as being mentioned in paragraph 14 rather than 18 where that string is?
- Want a way to limit to disagreements where quoted?  Might not - this is a start to assessing erroneous agreement.  If yes, 1 < coding time < 4 hours.

    - problem - `Reliability_Names.person_type` only has three values - "author", "subject", "source" - might need a row-level measure of "`has_mention`", "`has_quote`" to more readily capture rows where disagreement is over quoted-or-not.

## TODO - filter articles that are not news

- Back to [Table of Contents](#Table-of-Contents)

TODO:

- Article 22705 - Book roundup - probably should just remove from study, and see if meta-data about articles that could be used to automatically filter these type of articles out in the future.  Leaving in for now, but should flag these so I can do comparison of numbers with and without.
- Use keywords for Lakeshore section stories to try to filter out sports stories ("Basketball").  Maybe try this for all articles in the month?
- sports

## Debugging

- Back to [Table of Contents](#Table-of-Contents)

Issues to debug:

- TK

# DONE

- Back to [Table of Contents](#Table-of-Contents)

DONE:

# NEXT

- Back to [Table of Contents](#Table-of-Contents)